<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Zend\\' => array($vendorDir . '/zendframework/zendframework/library'),
    'ZendXml\\' => array($vendorDir . '/zendframework/zendxml/library'),
    'PhpBoletoZf2' => array($vendorDir . '/jotjunior/boletophp-zf2/src'),
    'DOMPDFModule' => array($vendorDir . '/dino/dompdf-module/src'),
);
